# Generated by Django 4.1.4 on 2022-12-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("macAddress", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("status", models.CharField(default="ONLINE", max_length=6)),
            ],
        ),
    ]
